### ISSUE TITLE
0.1.0 release

### ISSUE THREAD

**Issue by edmundnoble** [typelevel/cats-mtl#10]
Some pre-requisites for a 0.1.0 release are:
- The release of cats 1.0.0-MF
- ~Adding missing tests, laws, and syntax (#6, #7, #8)~
- Adding basic docs (#2, #3, #4)
- ~TraverseEmpty, for cats parity (#5)~

It would be nice to have a formulation for MonadBracket (#9) but it doesn't seem likely to appear in time.

I'm projecting that this will take a week and a half.

**Comment by kailuowang** [comment]
do you want to publish under `org.typelevel`?

**Comment by edmundnoble** [comment]
`org.typelevel` is fine. I'd like to move it soon.
