### ISSUE TITLE
Elect a new maintainer

### ISSUE THREAD

**Issue by andyscott** [typelevel/cats-mtl#16]
See https://github.com/typelevel/cats/issues/2018

**Comment by kailuowang** [comment]
in the past, we usually just have all cats maintainers automatically be maintainers of such cats module repos. We can then start adding new maintainers using the same process as cats.

**Comment by andyscott** [comment]
Makes sense to me. This was my ploy to get https://github.com/typelevel/cats-mtl/pull/15 merged.
