### ISSUE TITLE
Rewrite away the LayerControl stuff

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-mtl#189]
`MonadLayerControl` (and similar) are a clever mechanism for reducing the implementation boilerplate of MTL-like libraries (such as this one), but they also prevent such libraries from interacting with non-algebraic monad transformers, such as `FreeT`, `ContT`, and many more.

In order to avoid these issues, as well as make the library generally more maintainable and avoid some of the issues with implicit resolution, we should rewrite all of that away and use a more conventional lifting mechanism for each class. For trivial constructor algebras (such as `MonadState`), we can still do auto-lifting using a mechanism like scalaz's `MonadPartialOrder`, but non-algebraic effects (like `handleErrorWith` or `local`) need to be lifted more explicitly on a bespoke basis. This is, in fact, the greatest strength of the MTL approach: the fact that lifting those effects *is* tailored to the stack in question, rather than generalized in a way which causes unsoundness in certain permutations (such as the way in which `Eff` works).

**Comment by LukaJCB** [comment]
Done in #215
