### ISSUE TITLE
Add low-priority materializations for Handle in terms of ApplicativeError

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-mtl#255]
Given an `ApplicativeError[F, E]`, we should be able to get a `Handle[F, E]` (which implies `Raise[F, E]`). This would be very useful in that it allows us to get something like `Raise[IO, Throwable]`, which extends the generality of the library somewhat. It shouldn't cause any ambiguity issues if it is pushed to the lowest priority of the resolution chain in the `Handle` companion.

**Comment by pchpsky** [comment]
@djspiewak I'd like to solve this issue. I need to add instance of `Handle` for `ApplicativeError` in `HandleInstances`. Is it correct?

**Comment by djspiewak** [comment]
@pchpsky Almost! You need to create a `HandleLowPriorityInstances` which `HandleInstances` extends. This is what pushes the `ApplicativeError` materialization to a lower priority.

**Comment by pchpsky** [comment]
@djspiewak thank you. I'll work on this.
