### ISSUE TITLE
Consider to use `InstanceOf` scalaz pattern 

### ISSUE THREAD

**Issue by Odomontois** [typelevel/cats-mtl#26]
[This scalaz PR](https://github.com/scalaz/scalaz/pull/1647) targeting well-known ambigous-subtype implicit problem resolving it without repackaging base typeclass instances inside sub-typeclass es.

I wonder if this method is suitable for cats-mtl project. 

PR welcome?

**Comment by LukaJCB** [comment]
This sounds like a good idea to me, I haven't fully understood the pattern yet, but it seems to strike a good balance. We've always said `cats-mtl` is an experimental part of the ecosystem, so I'd love to see a PR :)

**Comment by SystemFw** [comment]
Yes, we should definitely see where this leads.

**Comment by andyscott** [comment]
Agreed! PR is definitely welcome.

**Comment by LukaJCB** [comment]
I wonder if we could get an experimental version of simulacrum with this type of encoding

**Comment by LukaJCB** [comment]
@Odomontois, are you working on this? If not I'd like to give this a shot.

**Comment by kamilkloch** [comment]
@LukaJCB I picked up the task.

**Comment by LukaJCB** [comment]
Closing in favor of #53
