### ISSUE TITLE
Mtl Class for catching errors

### ISSUE THREAD

**Issue by jvliwanag** [typelevel/cats-mtl#29]
There's `FunctorRaise` for raising errors. Should there also be an mtl class for catching errors?

**Comment by LukaJCB** [comment]
Good question. We already have `ApplicativeError` and `MonadError` in cats-core. I'm not sure myself if it makes sense to add another one here.

**Comment by jvliwanag** [comment]
Ran into this when dealing with `cats.effect.Sync` and custom error types:

```scala
def foo[F[_]](implicit S: cats.effect.Sync[F], ME: MonadError[F, Bar]): F[Unit] = {
    implicitly[Monad[F]].pure(())
  }
```

Resulting in:

```
[error]      ambiguous implicit values:
[error]       both value ME of type cats.MonadError[F,bolt.Bla.Bar]
[error]       and value S of type cats.effect.Sync[F]
[error]       match expected type cats.Monad[F]
```

**Comment by LukaJCB** [comment]
@jvliwanag `Sync` extends `MonadError[F, Throwable]`, so that's going to be a conflict there.
Unfortunately that is an unresolved problem in the type class encoding. To work around that particular case you can use `S.pure` instead, but I realize it might not be that simple in general :/

**Comment by jvliwanag** [comment]
Yup, which is why perhaps, creating an mtl class for catching errors would be beneficial. :) `FunctorRaise` + `Sync` already works nicely. Just need the catching part.

**Comment by LukaJCB** [comment]
That's true, though we'd end up with two different type classes for the same thing which is a bit of a shame.
I say we could try it out and make another class, since cats-mtl is still a somewhat young project and can benefit from experimentation :)
