### ISSUE TITLE
Release for Scala 3

### ISSUE THREAD

**Issue by justinhj** [typelevel/cats-mtl#347]
Having trouble getting this to work with Scala 3. Looks like it hasn't been released for 3.0.0?

**Comment by rossabaker** [comment]
Version 1.2.1 [is on Maven Central](https://repo1.maven.org/maven2/org/typelevel/cats-mtl_3/1.2.1/).

**Comment by justinhj** [comment]
If anyone is curious it was an sbt problem. I updated to 1.5.4 from 1.4 and it fixed the following resolution issue...

`[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.typelevel:cats-mtl_3.0:1.2.1`

**Comment by djspiewak** [comment]
Ah! Yes older versions of sbt don't understand the Scala 3 bincompat suffix.
