### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by edmundnoble** [typelevel/cats-mtl#4]
Have a nice explanatory README.md, which gives users the gist of the library. I also plan to fold DESIGN.md and CONTRIBUTING.md into this file, for easy discovery.

**Comment by benhutchison** [comment]
Please also include a guide to basic imports. I ended up stumbling on `cats-mtl` during a cats upgrade because I was using `filterA` (which used to be in cats), and a quick Getting Started would have sped me on my way.
