### ISSUE TITLE
Scaladoc link is invalid now

### ISSUE THREAD

**Issue by floating-cat** [typelevel/cats-mtl#440]
Two places:

1. In [homepage](https://typelevel.org/cats-mtl/index.html)'s right-top bar, click the doc link would go to https://www.javadoc.io/doc/org.typelevel/cats-mtl-docs_2.13/1.3.0/ and it will jump to the `javadoc.io`'s homepage with "Artifact org.typelevel:cats-mtl-docs_2.13 does not exist." error.
The right link seems to be https://www.javadoc.io/doc/org.typelevel/cats-mtl_2.13/.

2. In this repo's [markdown file](https://github.com/typelevel/cats-mtl#documentation), it uses the https://typelevel.org/cats-mtl/api/ for Scaladoc which would jump to the https://www.javadoc.io/doc/org.typelevel/cats-mtl-docs_2.13/1.3.0/ too.

**Comment by benhutchison** [comment]
I think the `unidocs` sbt project which is supposed to upload the `cats-mtl-docs` artifact isnt getting built.

I wonder if this advice is relevant
`// Make sure to add to your root aggregate so it gets published!`
https://typelevel.org/sbt-typelevel/site.html#how-can-i-publish-unidoc-api-docs

**Comment by tyukiand** [comment]
As of today (2023-03-21), both the link on the homepage and in the README.md are (again?) giving the

> Artifact org.typelevel:cats-mtl-docs_2.13 does not exist. 

error message on javadoc.io.

Could [this idea with the version bump](https://github.com/typelevel/cats-mtl/pull/459#issuecomment-1423566433) still be relevant?
